package model;
// Generated 17-may-2019 20:01:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCli;
     private String nomCli;
     private String apeCli;
     private Set logins = new HashSet(0);
     private Set registroUsuarios = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String nomCli, String apeCli) {
       this.nomCli = nomCli;
       this.apeCli = apeCli;
       
    }
    
    public Cliente(String nomCli, String apeCli, Set logins, Set registroUsuarios) {
       this.nomCli = nomCli;
       this.apeCli = apeCli;
       this.logins = logins;
       this.registroUsuarios = registroUsuarios;
    }
   
    public Integer getCodCli() {
        return this.codCli;
    }
    
    public void setCodCli(Integer codCli) {
        this.codCli = codCli;
    }
    public String getNomCli() {
        return this.nomCli;
    }
    
    public void setNomCli(String nomCli) {
        this.nomCli = nomCli;
    }
    public String getApeCli() {
        return this.apeCli;
    }
    
    public void setApeCli(String apeCli) {
        this.apeCli = apeCli;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getRegistroUsuarios() {
        return this.registroUsuarios;
    }
    
    public void setRegistroUsuarios(Set registroUsuarios) {
        this.registroUsuarios = registroUsuarios;
    }




}


