package model;
// Generated 17-may-2019 20:01:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegistroUsuario generated by hbm2java
 */
public class RegistroUsuario  implements java.io.Serializable {


     private Integer codReg;
     private Cliente cliente;
     private Date fechaEnt;
     private Date fechaSal;

    public RegistroUsuario() {
    }

    public RegistroUsuario(Cliente cliente, Date fechaEnt, Date fechaSal) {
       this.cliente = cliente;
       this.fechaEnt = fechaEnt;
       this.fechaSal = fechaSal;
    }
   
    public Integer getCodReg() {
        return this.codReg;
    }
    
    public void setCodReg(Integer codReg) {
        this.codReg = codReg;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaEnt() {
        return this.fechaEnt;
    }
    
    public void setFechaEnt(Date fechaEnt) {
        this.fechaEnt = fechaEnt;
    }
    public Date getFechaSal() {
        return this.fechaSal;
    }
    
    public void setFechaSal(Date fechaSal) {
        this.fechaSal = fechaSal;
    }




}


